apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kompozer
resources:
  - 00-namespace.yaml
  - 01-secrets.yaml
  - 10-redis.yaml
  - 11-mongo-databases.yaml
  - 12-mongo-cad-rs.yaml
  - 20-auth-service.yaml
  - 21-catalog-service.yaml
  - 22-cart-service.yaml
  - 23-order-service.yaml
  - 24-cad-service.yaml
  - 25-notification-service.yaml
  - 26-chatbot-service.yaml
  - 27-reporting-service.yaml
  - 30-api-gateway.yaml
